name       : amule
version    : 2.3.2
release    : 4
source     :
    - https://github.com/amule-project/amule/archive/2.3.2.tar.gz : 62fe4993bd53cfc829a823cec52194589feb78339777c1caef03fc9e2c906cf3
license    : GPL-2.0
component  : network.util
summary    : aMule is a multi-platform ed2k client, fork of the eMule client
description: |
    aMule is a multi-platform ed2k client, fork of the eMule client
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(libpng)
    - pkgconfig(libupnp)
    - cryptopp-devel
    - wxwidgets2.8-devel
setup      : |
    ./autogen.sh
    %configure --with-wx-config=wx-config-2.8
build      : |
    %make
install    : |
    %make_install
