name       : amule
version    : 2.3.2
release    : 9
source     :
    - git|https://github.com/amule-project/amule : 2.3.2
license    : GPL-2.0
component  : network.util
summary    : aMule is a multi-platform ed2k client, fork of the eMule client
description: |
    aMule is a multi-platform ed2k client, fork of the eMule client
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig(libpng)
    - pkgconfig(libupnp)
    - cryptopp-devel
    - wxwidgets2.8-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-bugfix-API-mismatch-with-cryptopp.patch
    %autogen --with-wx-config=wx-config-2.8
build      : |
    %make
install    : |
    %make_install
